language: go
go:
 - 1.2
 - release
 - tip
before_install:
 - sudo apt-get update
 - sudo apt-get install -y libusb-dev # littlewire uses < 1.0 version of libusb
install:
 - go get -v . && go build -v .
 - go get github.com/onsi/ginkgo
 - go get github.com/onsi/gomega
 - go get code.google.com/p/go.tools/cmd/cover
 #- go get github.com/mattn/goveralls
script:
 - go test -covermode=count -coverprofile=profile.cov github.com/hybridgroup/gobot-digispark
 - export PATH=$PATH:$HOME/gopath/bin/
 #- goveralls -coverprofile=profile.cov -service=travis-ci -repotoken=sFrR9ZmLP5FLc34lOaqir67RPzYOvFPUB
